# name: Code-check
# on: 
#   push:
#     branches:
#       - master
#   pull_request:
#       types: [opened, synchronize, reopened]   
# jobs: 
#   build:
#     name: SonarQube
#     runs-on: dsb_ubuntu
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         # Disabling shallow clone is recommended for improving relevancy of reporting
#         fetch-depth: 0
#       # Triggering SonarQube analysis as results of it are required by Quality Gate check
#     - name: SonarQube Scan
#       uses: sonarsource/sonarqube-scan-action@master 
#       with: 
#         args: >
#           -Dsonar.projectKey=react-seal-test 
#       env:
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 
