name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]  
env:
  AZURE_WEBAPP_NAME: react-seal-test    
  AZURE_WEBAPP_PACKAGE_PATH: '.'              
  NODE_VERSION: '16.x' 
jobs: 
  build-and-deploy: 
    name: Build and Deploy
    runs-on: ubuntu-latest 
    
    env:
      NODE_ENV: test
      REACT_APP_SERKAN: 'serkan: from envenv0'
      REACT_APP_SEAL: 'seal: from envenv0'
      SERKAN: 'serkan: from envenv00'
      SEAL: 'seal: from envenv00'
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }} 
        REACT_APP_SERKAN: 'serkan: from envwidth1'
        REACT_APP_SEAL: 'seal: from envwidth1'
      env:
          REACT_APP_SERKAN: 'serkan: from envenv2'
          REACT_APP_SEAL: 'seal: from envenv2'
    
    - name: npm install, build, and test
      run: | 
        npm install
        npm run build --if-present

      env:
        SERKAN: 123
        REACT_APP_SERKAN: 321

    - name: create env file
      run: |
        touch .env
        echo REACT_APP_SERKAN=shit >> .env

    - name: add process.json
      run: |
        echo '{ script: "serve", env: { PM2_SERVE_SPA: "true", PM2_SERVE_HOMEPAGE: "/index.html" } }' >> build/process.json
          
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
