# name: CI/CD
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#       types: [opened, synchronize, reopened]  
# env:
#   AZURE_WEBAPP_NAME: react-seal-test    
#   AZURE_WEBAPP_PACKAGE_PATH: '.'              
#   NODE_VERSION: '16.x' 
#   REACT_APP_SERKAN: 'build'

# jobs: 
#   build-and-deploy: 
#     name: Build and Deploy
#     runs-on: ubuntu-latest 
    
#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ env.NODE_VERSION }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ env.NODE_VERSION }} 

#     - name: npm install, build, and test
#       run: | 
#         npm install
#         npm run build --if-present 

#     - name: add process.json
#       run: |
#         echo '{ script: "serve", env: { PM2_SERVE_SPA: "true", PM2_SERVE_HOMEPAGE: "/index.html" } }' >> build/process.json
          
#     - name: 'Deploy to Azure WebApp'
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: ${{ env.AZURE_WEBAPP_NAME }}
#         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}



name: CI/CD
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: react-seal-test    
  AZURE_WEBAPP_PACKAGE_PATH: '.'              
  NODE_VERSION: '16.x' 
  REACT_APP_SERKAN: 'build'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install & build
        run: |
          npm install
          npm run build --if-present
          
      - name: Zip artifact for deployment 
        run: zip -r release.zip * .env .next

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      name: 'dev'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
 
      - name: Unzip artifact for deployment
        run: unzip release.zip 
    
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}