name: ci/cd
on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]  
env:
  AZURE_WEBAPP_NAME: react-seal-test   
  AZURE_WEBAPP_PACKAGE_PATH: '.'      
  NODE_VERSION: '16.x'     

jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }} 

      - name: add .env file
        run: |
          touch .env
          echo REACT_APP_SERKAN_2 =${{ secrets.REACT_APP_SERKAN_2 }} >> .env
          echo REACT_APP_SERKAN =${{ secrets.REACT_APP_SERKAN }} >> .env

      - name: npm install, build, and test
        run: | 
          npm install
          npm run build --if-present 
        env:
          CI: false

      - name: add process.json
        run: |
          echo '{ script: "serve", env: { PM2_SERVE_SPA: "true", PM2_SERVE_HOMEPAGE: "/index.html" } }' >> build/process.json
          
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9FF70FCC318742C9B34DB0350AED6B07 }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}