name: ci
on:
  push:
    branches:
      - main
      - feature/**  
  workflow_dispatch:

env:   
  NODE_VERSION: '16.x'     

permissions:
  contents: read
  
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }} 

      - name: npm install, build, and test
        run: | 
          npm install
          npm run build --if-present 
        env:
          CI: false