# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: yolo

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: react-seal-test   
  AZURE_WEBAPP_PACKAGE_PATH: 'build'      
  NODE_VERSION: '16.x'               

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: add .env file
        run: |
          touch .env
          echo REACT_APP_SERKAN_2 =${{ secrets.REACT_APP_SERKAN_2 }} >> .env
          echo REACT_APP_SERKAN =${{ secrets.REACT_APP_SERKAN }} >> .env

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment 
        run: zip -r app.zip * .env .next

      # - name: add process.json
      #   run: |
      #   echo ‘{ script: “serve”, env: { PM2_SERVE_SPA: “true”, PM2_SERVE_HOMEPAGE: “/index.html” } }’ >> build/process.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v23
        with:
          name: node-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip app.zip 

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9FF70FCC318742C9B34DB0350AED6B07 }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

