name: newcicd
on:
  push:
    branches: 
    - main
  
env:
  AZURE_WEBAPP_NAME: react-seal-test 
  AZURE_WEBAPP_PACKAGE_PATH: '.'      
  NODE_VERSION: '16.x'     

jobs: 
  # build-and-deploy: 
  #   runs-on: ubuntu-latest  
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Node.js version
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ env.NODE_VERSION }} 

  #     - name: npm install, build, and test
  #       run: | 
  #         npm install
  #         npm run build --if-present 
  #       env:
  #         CI: false

  #     - name: add process.json
  #       run: |
  #         echo '{ script: "serve", env: { PM2_SERVE_SPA: "true", PM2_SERVE_HOMEPAGE: "/index.html" } }' >> build/process.json
          
  #     - name: 'Deploy to Azure WebApp'
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ env.AZURE_WEBAPP_NAME }} 
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
 
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }} 

      - name: npm install, build, and test
        run: | 
          npm install
          npm run build --if-present  
  
      - name: Zip all files for upload between jobs
        run: zip release.zip ./* .release -qr

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} 
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip